# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 22 Jun 2017 03:00:39 +0000
*	@ALL	1
*	@user	2
*	@cster	8
inner:*	@ALL	0
inner:*	@admin	16
management:admin:*	@ALL	0
inner:*	@cster	8
management:*	@cster	8
